export namespace Flag {
  // Helper to get env var with new name first, fallback to legacy
  function envWithFallback(newName: string, legacyName: string): string | undefined {
    return process.env[newName] ?? process.env[legacyName]
  }

  function truthyWithFallback(newName: string, legacyName: string): boolean {
    const value = (process.env[newName] ?? process.env[legacyName])?.toLowerCase()
    return value === "true" || value === "1"
  }

  function numberWithFallback(newName: string, legacyName: string): number | undefined {
    const value = process.env[newName] ?? process.env[legacyName]
    if (!value) return undefined
    const parsed = Number(value)
    return Number.isInteger(parsed) && parsed > 0 ? parsed : undefined
  }

  // New BASE_ONE_* env vars with fallback to OPENCODE_*
  export const BASE_ONE_AUTO_SHARE = truthyWithFallback("BASE_ONE_AUTO_SHARE", "OPENCODE_AUTO_SHARE")
  export const BASE_ONE_GIT_BASH_PATH = envWithFallback("BASE_ONE_GIT_BASH_PATH", "OPENCODE_GIT_BASH_PATH")
  export const BASE_ONE_CONFIG = envWithFallback("BASE_ONE_CONFIG", "OPENCODE_CONFIG")
  export const BASE_ONE_CONFIG_DIR = envWithFallback("BASE_ONE_CONFIG_DIR", "OPENCODE_CONFIG_DIR")
  export const BASE_ONE_CONFIG_CONTENT = envWithFallback("BASE_ONE_CONFIG_CONTENT", "OPENCODE_CONFIG_CONTENT")
  export const BASE_ONE_DISABLE_AUTOUPDATE = truthyWithFallback("BASE_ONE_DISABLE_AUTOUPDATE", "OPENCODE_DISABLE_AUTOUPDATE")
  export const BASE_ONE_DISABLE_PRUNE = truthyWithFallback("BASE_ONE_DISABLE_PRUNE", "OPENCODE_DISABLE_PRUNE")
  export const BASE_ONE_DISABLE_TERMINAL_TITLE = truthyWithFallback("BASE_ONE_DISABLE_TERMINAL_TITLE", "OPENCODE_DISABLE_TERMINAL_TITLE")
  export const BASE_ONE_PERMISSION = envWithFallback("BASE_ONE_PERMISSION", "OPENCODE_PERMISSION")
  export const BASE_ONE_DISABLE_DEFAULT_PLUGINS = truthyWithFallback("BASE_ONE_DISABLE_DEFAULT_PLUGINS", "OPENCODE_DISABLE_DEFAULT_PLUGINS")
  export const BASE_ONE_DISABLE_LSP_DOWNLOAD = truthyWithFallback("BASE_ONE_DISABLE_LSP_DOWNLOAD", "OPENCODE_DISABLE_LSP_DOWNLOAD")
  export const BASE_ONE_ENABLE_EXPERIMENTAL_MODELS = truthyWithFallback("BASE_ONE_ENABLE_EXPERIMENTAL_MODELS", "OPENCODE_ENABLE_EXPERIMENTAL_MODELS")
  export const BASE_ONE_DISABLE_AUTOCOMPACT = truthyWithFallback("BASE_ONE_DISABLE_AUTOCOMPACT", "OPENCODE_DISABLE_AUTOCOMPACT")
  export const BASE_ONE_DISABLE_MODELS_FETCH = truthyWithFallback("BASE_ONE_DISABLE_MODELS_FETCH", "OPENCODE_DISABLE_MODELS_FETCH")
  export const BASE_ONE_FAKE_VCS = envWithFallback("BASE_ONE_FAKE_VCS", "OPENCODE_FAKE_VCS")
  export const BASE_ONE_CLIENT = envWithFallback("BASE_ONE_CLIENT", "OPENCODE_CLIENT") ?? "cli"

  // Experimental
  export const BASE_ONE_EXPERIMENTAL = truthyWithFallback("BASE_ONE_EXPERIMENTAL", "OPENCODE_EXPERIMENTAL")
  export const BASE_ONE_EXPERIMENTAL_FILEWATCHER = truthyWithFallback("BASE_ONE_EXPERIMENTAL_FILEWATCHER", "OPENCODE_EXPERIMENTAL_FILEWATCHER")
  export const BASE_ONE_EXPERIMENTAL_DISABLE_FILEWATCHER = truthyWithFallback("BASE_ONE_EXPERIMENTAL_DISABLE_FILEWATCHER", "OPENCODE_EXPERIMENTAL_DISABLE_FILEWATCHER")
  export const BASE_ONE_EXPERIMENTAL_ICON_DISCOVERY =
    BASE_ONE_EXPERIMENTAL || truthyWithFallback("BASE_ONE_EXPERIMENTAL_ICON_DISCOVERY", "OPENCODE_EXPERIMENTAL_ICON_DISCOVERY")
  export const BASE_ONE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT = truthyWithFallback("BASE_ONE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT", "OPENCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT")
  export const BASE_ONE_ENABLE_EXA =
    truthyWithFallback("BASE_ONE_ENABLE_EXA", "OPENCODE_ENABLE_EXA") || BASE_ONE_EXPERIMENTAL || truthyWithFallback("BASE_ONE_EXPERIMENTAL_EXA", "OPENCODE_EXPERIMENTAL_EXA")
  export const BASE_ONE_EXPERIMENTAL_BASH_MAX_OUTPUT_LENGTH = numberWithFallback("BASE_ONE_EXPERIMENTAL_BASH_MAX_OUTPUT_LENGTH", "OPENCODE_EXPERIMENTAL_BASH_MAX_OUTPUT_LENGTH")
  export const BASE_ONE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS = numberWithFallback("BASE_ONE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS", "OPENCODE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS")
  export const BASE_ONE_EXPERIMENTAL_OUTPUT_TOKEN_MAX = numberWithFallback("BASE_ONE_EXPERIMENTAL_OUTPUT_TOKEN_MAX", "OPENCODE_EXPERIMENTAL_OUTPUT_TOKEN_MAX")
  export const BASE_ONE_EXPERIMENTAL_OXFMT = BASE_ONE_EXPERIMENTAL || truthyWithFallback("BASE_ONE_EXPERIMENTAL_OXFMT", "OPENCODE_EXPERIMENTAL_OXFMT")
  export const BASE_ONE_EXPERIMENTAL_LSP_TY = truthyWithFallback("BASE_ONE_EXPERIMENTAL_LSP_TY", "OPENCODE_EXPERIMENTAL_LSP_TY")

  // Legacy aliases for backwards compatibility during migration
  export const OPENCODE_AUTO_SHARE = BASE_ONE_AUTO_SHARE
  export const OPENCODE_GIT_BASH_PATH = BASE_ONE_GIT_BASH_PATH
  export const OPENCODE_CONFIG = BASE_ONE_CONFIG
  export const OPENCODE_CONFIG_DIR = BASE_ONE_CONFIG_DIR
  export const OPENCODE_CONFIG_CONTENT = BASE_ONE_CONFIG_CONTENT
  export const OPENCODE_DISABLE_AUTOUPDATE = BASE_ONE_DISABLE_AUTOUPDATE
  export const OPENCODE_DISABLE_PRUNE = BASE_ONE_DISABLE_PRUNE
  export const OPENCODE_DISABLE_TERMINAL_TITLE = BASE_ONE_DISABLE_TERMINAL_TITLE
  export const OPENCODE_PERMISSION = BASE_ONE_PERMISSION
  export const OPENCODE_DISABLE_DEFAULT_PLUGINS = BASE_ONE_DISABLE_DEFAULT_PLUGINS
  export const OPENCODE_DISABLE_LSP_DOWNLOAD = BASE_ONE_DISABLE_LSP_DOWNLOAD
  export const OPENCODE_ENABLE_EXPERIMENTAL_MODELS = BASE_ONE_ENABLE_EXPERIMENTAL_MODELS
  export const OPENCODE_DISABLE_AUTOCOMPACT = BASE_ONE_DISABLE_AUTOCOMPACT
  export const OPENCODE_DISABLE_MODELS_FETCH = BASE_ONE_DISABLE_MODELS_FETCH
  export const OPENCODE_FAKE_VCS = BASE_ONE_FAKE_VCS
  export const OPENCODE_CLIENT = BASE_ONE_CLIENT
  export const OPENCODE_EXPERIMENTAL = BASE_ONE_EXPERIMENTAL
  export const OPENCODE_EXPERIMENTAL_FILEWATCHER = BASE_ONE_EXPERIMENTAL_FILEWATCHER
  export const OPENCODE_EXPERIMENTAL_DISABLE_FILEWATCHER = BASE_ONE_EXPERIMENTAL_DISABLE_FILEWATCHER
  export const OPENCODE_EXPERIMENTAL_ICON_DISCOVERY = BASE_ONE_EXPERIMENTAL_ICON_DISCOVERY
  export const OPENCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT = BASE_ONE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT
  export const OPENCODE_ENABLE_EXA = BASE_ONE_ENABLE_EXA
  export const OPENCODE_EXPERIMENTAL_BASH_MAX_OUTPUT_LENGTH = BASE_ONE_EXPERIMENTAL_BASH_MAX_OUTPUT_LENGTH
  export const OPENCODE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS = BASE_ONE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS
  export const OPENCODE_EXPERIMENTAL_OUTPUT_TOKEN_MAX = BASE_ONE_EXPERIMENTAL_OUTPUT_TOKEN_MAX
  export const OPENCODE_EXPERIMENTAL_OXFMT = BASE_ONE_EXPERIMENTAL_OXFMT
  export const OPENCODE_EXPERIMENTAL_LSP_TY = BASE_ONE_EXPERIMENTAL_LSP_TY
}
