import { Config } from "effect"
import { InstallationChannel } from "../installation/version"

function truthy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "true" || value === "1"
}

function falsy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "false" || value === "0"
}

// Channels that default to the new effect-httpapi server backend. The legacy
// hono backend remains the default for stable (`prod`/`latest`) installs.
const HTTPAPI_DEFAULT_ON_CHANNELS = new Set(["dev", "beta", "local"])

function number(key: string) {
  const value = process.env[key]
  if (!value) return undefined
  const parsed = Number(value)
  return Number.isInteger(parsed) && parsed > 0 ? parsed : undefined
}

function envWithFallback(primary: string, fallback: string) {
  return process.env[primary] ?? process.env[fallback]
}

function truthyWithFallback(primary: string, fallback: string) {
  return truthy(primary) || truthy(fallback)
}

function numberWithFallback(primary: string, fallback: string) {
  return number(primary) ?? number(fallback)
}

const OPENCODE_EXPERIMENTAL = truthy("OPENCODE_EXPERIMENTAL")
const OPENCODE_DISABLE_CLAUDE_CODE = truthy("OPENCODE_DISABLE_CLAUDE_CODE")
const OPENCODE_DISABLE_CLAUDE_CODE_SKILLS =
  OPENCODE_DISABLE_CLAUDE_CODE || truthy("OPENCODE_DISABLE_CLAUDE_CODE_SKILLS")
const copy = process.env["OPENCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"]

const BASEONE_EXPERIMENTAL = truthyWithFallback("BASEONE_EXPERIMENTAL", "OPENCODE_EXPERIMENTAL")
const BASEONE_DISABLE_CLAUDE_CODE = truthyWithFallback("BASEONE_DISABLE_CLAUDE_CODE", "OPENCODE_DISABLE_CLAUDE_CODE")
const BASEONE_DISABLE_CLAUDE_CODE_SKILLS =
  BASEONE_DISABLE_CLAUDE_CODE || truthyWithFallback("BASEONE_DISABLE_CLAUDE_CODE_SKILLS", "OPENCODE_DISABLE_CLAUDE_CODE_SKILLS")
const baseoneCopy = envWithFallback("BASEONE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT", "OPENCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT")

export const Flag = {
  OTEL_EXPORTER_OTLP_ENDPOINT: process.env["OTEL_EXPORTER_OTLP_ENDPOINT"],
  OTEL_EXPORTER_OTLP_HEADERS: process.env["OTEL_EXPORTER_OTLP_HEADERS"],

  OPENCODE_AUTO_SHARE: truthyWithFallback("BASEONE_AUTO_SHARE", "OPENCODE_AUTO_SHARE"),
  OPENCODE_AUTO_HEAP_SNAPSHOT: truthyWithFallback("BASEONE_AUTO_HEAP_SNAPSHOT", "OPENCODE_AUTO_HEAP_SNAPSHOT"),
  OPENCODE_GIT_BASH_PATH: envWithFallback("BASEONE_GIT_BASH_PATH", "OPENCODE_GIT_BASH_PATH"),
  OPENCODE_CONFIG: envWithFallback("BASEONE_CONFIG", "OPENCODE_CONFIG"),
  OPENCODE_CONFIG_CONTENT: envWithFallback("BASEONE_CONFIG_CONTENT", "OPENCODE_CONFIG_CONTENT"),
  OPENCODE_DISABLE_AUTOUPDATE: truthyWithFallback("BASEONE_DISABLE_AUTOUPDATE", "OPENCODE_DISABLE_AUTOUPDATE"),
  OPENCODE_ALWAYS_NOTIFY_UPDATE: truthyWithFallback("BASEONE_ALWAYS_NOTIFY_UPDATE", "OPENCODE_ALWAYS_NOTIFY_UPDATE"),
  OPENCODE_DISABLE_PRUNE: truthyWithFallback("BASEONE_DISABLE_PRUNE", "OPENCODE_DISABLE_PRUNE"),
  OPENCODE_DISABLE_TERMINAL_TITLE: truthyWithFallback("BASEONE_DISABLE_TERMINAL_TITLE", "OPENCODE_DISABLE_TERMINAL_TITLE"),
  OPENCODE_SHOW_TTFD: truthyWithFallback("BASEONE_SHOW_TTFD", "OPENCODE_SHOW_TTFD"),
  OPENCODE_PERMISSION: envWithFallback("BASEONE_PERMISSION", "OPENCODE_PERMISSION"),
  OPENCODE_DISABLE_DEFAULT_PLUGINS: truthyWithFallback("BASEONE_DISABLE_DEFAULT_PLUGINS", "OPENCODE_DISABLE_DEFAULT_PLUGINS"),
  OPENCODE_DISABLE_LSP_DOWNLOAD: truthyWithFallback("BASEONE_DISABLE_LSP_DOWNLOAD", "OPENCODE_DISABLE_LSP_DOWNLOAD"),
  OPENCODE_ENABLE_EXPERIMENTAL_MODELS: truthyWithFallback("BASEONE_ENABLE_EXPERIMENTAL_MODELS", "OPENCODE_ENABLE_EXPERIMENTAL_MODELS"),
  OPENCODE_DISABLE_AUTOCOMPACT: truthyWithFallback("BASEONE_DISABLE_AUTOCOMPACT", "OPENCODE_DISABLE_AUTOCOMPACT"),
  OPENCODE_DISABLE_MODELS_FETCH: truthyWithFallback("BASEONE_DISABLE_MODELS_FETCH", "OPENCODE_DISABLE_MODELS_FETCH"),
  OPENCODE_DISABLE_MOUSE: truthyWithFallback("BASEONE_DISABLE_MOUSE", "OPENCODE_DISABLE_MOUSE"),
  OPENCODE_DISABLE_CLAUDE_CODE: BASEONE_DISABLE_CLAUDE_CODE,
  OPENCODE_DISABLE_CLAUDE_CODE_PROMPT: BASEONE_DISABLE_CLAUDE_CODE || truthyWithFallback("BASEONE_DISABLE_CLAUDE_CODE_PROMPT", "OPENCODE_DISABLE_CLAUDE_CODE_PROMPT"),
  OPENCODE_DISABLE_CLAUDE_CODE_SKILLS: BASEONE_DISABLE_CLAUDE_CODE_SKILLS,
  OPENCODE_DISABLE_EXTERNAL_SKILLS: BASEONE_DISABLE_CLAUDE_CODE_SKILLS || truthyWithFallback("BASEONE_DISABLE_EXTERNAL_SKILLS", "OPENCODE_DISABLE_EXTERNAL_SKILLS"),
  OPENCODE_FAKE_VCS: envWithFallback("BASEONE_FAKE_VCS", "OPENCODE_FAKE_VCS"),
  OPENCODE_SERVER_PASSWORD: envWithFallback("BASEONE_SERVER_PASSWORD", "OPENCODE_SERVER_PASSWORD"),
  OPENCODE_SERVER_USERNAME: envWithFallback("BASEONE_SERVER_USERNAME", "OPENCODE_SERVER_USERNAME"),
  OPENCODE_ENABLE_QUESTION_TOOL: truthyWithFallback("BASEONE_ENABLE_QUESTION_TOOL", "OPENCODE_ENABLE_QUESTION_TOOL"),

  OPENCODE_EXPERIMENTAL: BASEONE_EXPERIMENTAL,
  OPENCODE_EXPERIMENTAL_FILEWATCHER: Config.boolean("OPENCODE_EXPERIMENTAL_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  OPENCODE_EXPERIMENTAL_DISABLE_FILEWATCHER: Config.boolean("OPENCODE_EXPERIMENTAL_DISABLE_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  OPENCODE_EXPERIMENTAL_ICON_DISCOVERY: BASEONE_EXPERIMENTAL || truthyWithFallback("BASEONE_EXPERIMENTAL_ICON_DISCOVERY", "OPENCODE_EXPERIMENTAL_ICON_DISCOVERY"),
  OPENCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT:
    baseoneCopy === undefined ? process.platform === "win32" : truthyWithFallback("BASEONE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT", "OPENCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"),
  OPENCODE_ENABLE_EXA: truthyWithFallback("BASEONE_ENABLE_EXA", "OPENCODE_ENABLE_EXA") || BASEONE_EXPERIMENTAL || truthyWithFallback("BASEONE_EXPERIMENTAL_EXA", "OPENCODE_EXPERIMENTAL_EXA"),
  OPENCODE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS: numberWithFallback("BASEONE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS", "OPENCODE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS"),
  OPENCODE_EXPERIMENTAL_OUTPUT_TOKEN_MAX: numberWithFallback("BASEONE_EXPERIMENTAL_OUTPUT_TOKEN_MAX", "OPENCODE_EXPERIMENTAL_OUTPUT_TOKEN_MAX"),
  OPENCODE_EXPERIMENTAL_OXFMT: BASEONE_EXPERIMENTAL || truthyWithFallback("BASEONE_EXPERIMENTAL_OXFMT", "OPENCODE_EXPERIMENTAL_OXFMT"),
  OPENCODE_EXPERIMENTAL_LSP_TY: truthyWithFallback("BASEONE_EXPERIMENTAL_LSP_TY", "OPENCODE_EXPERIMENTAL_LSP_TY"),
  OPENCODE_EXPERIMENTAL_LSP_TOOL: BASEONE_EXPERIMENTAL || truthyWithFallback("BASEONE_EXPERIMENTAL_LSP_TOOL", "OPENCODE_EXPERIMENTAL_LSP_TOOL"),
  OPENCODE_EXPERIMENTAL_PLAN_MODE: BASEONE_EXPERIMENTAL || truthyWithFallback("BASEONE_EXPERIMENTAL_PLAN_MODE", "OPENCODE_EXPERIMENTAL_PLAN_MODE"),
  OPENCODE_EXPERIMENTAL_MARKDOWN: !falsy("OPENCODE_EXPERIMENTAL_MARKDOWN"),
  OPENCODE_MODELS_URL: envWithFallback("BASEONE_MODELS_URL", "OPENCODE_MODELS_URL"),
  OPENCODE_MODELS_PATH: envWithFallback("BASEONE_MODELS_PATH", "OPENCODE_MODELS_PATH"),
  OPENCODE_DISABLE_EMBEDDED_WEB_UI: truthyWithFallback("BASEONE_DISABLE_EMBEDDED_WEB_UI", "OPENCODE_DISABLE_EMBEDDED_WEB_UI"),
  OPENCODE_DB: envWithFallback("BASEONE_DB", "OPENCODE_DB"),
  OPENCODE_DISABLE_CHANNEL_DB: truthyWithFallback("BASEONE_DISABLE_CHANNEL_DB", "OPENCODE_DISABLE_CHANNEL_DB"),
  OPENCODE_SKIP_MIGRATIONS: truthyWithFallback("BASEONE_SKIP_MIGRATIONS", "OPENCODE_SKIP_MIGRATIONS"),
  OPENCODE_STRICT_CONFIG_DEPS: truthyWithFallback("BASEONE_STRICT_CONFIG_DEPS", "OPENCODE_STRICT_CONFIG_DEPS"),

  OPENCODE_WORKSPACE_ID: envWithFallback("BASEONE_WORKSPACE_ID", "OPENCODE_WORKSPACE_ID"),
  OPENCODE_EXPERIMENTAL_HTTPAPI:
    truthyWithFallback("BASEONE_EXPERIMENTAL_HTTPAPI", "OPENCODE_EXPERIMENTAL_HTTPAPI") ||
    (!falsy("OPENCODE_EXPERIMENTAL_HTTPAPI") && HTTPAPI_DEFAULT_ON_CHANNELS.has(InstallationChannel)),
  OPENCODE_EXPERIMENTAL_WORKSPACES: BASEONE_EXPERIMENTAL || truthyWithFallback("BASEONE_EXPERIMENTAL_WORKSPACES", "OPENCODE_EXPERIMENTAL_WORKSPACES"),
  OPENCODE_EXPERIMENTAL_EVENT_SYSTEM: BASEONE_EXPERIMENTAL || truthyWithFallback("BASEONE_EXPERIMENTAL_EVENT_SYSTEM", "OPENCODE_EXPERIMENTAL_EVENT_SYSTEM"),

  BASEONE_EXPERIMENTAL,
  BASEONE_DISABLE_CLAUDE_CODE,
  BASEONE_DISABLE_CLAUDE_CODE_SKILLS,

  get OPENCODE_DISABLE_PROJECT_CONFIG() {
    return truthyWithFallback("BASEONE_DISABLE_PROJECT_CONFIG", "OPENCODE_DISABLE_PROJECT_CONFIG")
  },
  get OPENCODE_TUI_CONFIG() {
    return envWithFallback("BASEONE_TUI_CONFIG", "OPENCODE_TUI_CONFIG")
  },
  get OPENCODE_CONFIG_DIR() {
    return envWithFallback("BASEONE_CONFIG_DIR", "OPENCODE_CONFIG_DIR")
  },
  get OPENCODE_PURE() {
    return truthyWithFallback("BASEONE_PURE", "OPENCODE_PURE")
  },
  get OPENCODE_PLUGIN_META_FILE() {
    return envWithFallback("BASEONE_PLUGIN_META_FILE", "OPENCODE_PLUGIN_META_FILE")
  },
  get OPENCODE_CLIENT() {
    return envWithFallback("BASEONE_CLIENT", "OPENCODE_CLIENT") ?? "cli"
  },

  get BASEONE_DISABLE_PROJECT_CONFIG() {
    return truthy("BASEONE_DISABLE_PROJECT_CONFIG")
  },
  get BASEONE_TUI_CONFIG() {
    return process.env["BASEONE_TUI_CONFIG"]
  },
  get BASEONE_CONFIG_DIR() {
    return process.env["BASEONE_CONFIG_DIR"]
  },
  get BASEONE_PURE() {
    return truthy("BASEONE_PURE")
  },
  get BASEONE_PLUGIN_META_FILE() {
    return process.env["BASEONE_PLUGIN_META_FILE"]
  },
  get BASEONE_CLIENT() {
    return process.env["BASEONE_CLIENT"] ?? "cli"
  },
}
