import { Config } from "effect"

export function truthy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "true" || value === "1"
}

function envWithFallback(primary: string, fallback: string) {
  return process.env[primary] ?? process.env[fallback]
}

function enabledByExperimental(key: string) {
  return process.env[key] === undefined ? truthyWithFallback("BASEONE_EXPERIMENTAL", "OPENCODE_EXPERIMENTAL") : truthy(key)
}

function truthyWithFallback(primary: string, fallback: string) {
  return truthy(primary) || truthy(fallback)
}

const BASEONE_EXPERIMENTAL = truthyWithFallback("BASEONE_EXPERIMENTAL", "OPENCODE_EXPERIMENTAL")
const baseoneCopy = envWithFallback("BASEONE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT", "OPENCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT")

export const Flag = {
  OTEL_EXPORTER_OTLP_ENDPOINT: process.env["OTEL_EXPORTER_OTLP_ENDPOINT"],
  OTEL_EXPORTER_OTLP_HEADERS: process.env["OTEL_EXPORTER_OTLP_HEADERS"],

  OPENCODE_AUTO_HEAP_SNAPSHOT: truthyWithFallback("BASEONE_AUTO_HEAP_SNAPSHOT", "OPENCODE_AUTO_HEAP_SNAPSHOT"),
  OPENCODE_GIT_BASH_PATH: envWithFallback("BASEONE_GIT_BASH_PATH", "OPENCODE_GIT_BASH_PATH"),
  OPENCODE_CONFIG: envWithFallback("BASEONE_CONFIG", "OPENCODE_CONFIG"),
  OPENCODE_CONFIG_CONTENT: envWithFallback("BASEONE_CONFIG_CONTENT", "OPENCODE_CONFIG_CONTENT"),
  OPENCODE_DISABLE_AUTOUPDATE: truthyWithFallback("BASEONE_DISABLE_AUTOUPDATE", "OPENCODE_DISABLE_AUTOUPDATE"),
  OPENCODE_ALWAYS_NOTIFY_UPDATE: truthyWithFallback("BASEONE_ALWAYS_NOTIFY_UPDATE", "OPENCODE_ALWAYS_NOTIFY_UPDATE"),
  OPENCODE_DISABLE_PRUNE: truthyWithFallback("BASEONE_DISABLE_PRUNE", "OPENCODE_DISABLE_PRUNE"),
  OPENCODE_DISABLE_TERMINAL_TITLE: truthyWithFallback("BASEONE_DISABLE_TERMINAL_TITLE", "OPENCODE_DISABLE_TERMINAL_TITLE"),
  OPENCODE_SHOW_TTFD: truthyWithFallback("BASEONE_SHOW_TTFD", "OPENCODE_SHOW_TTFD"),
  OPENCODE_PERMISSION: envWithFallback("BASEONE_PERMISSION", "OPENCODE_PERMISSION"),
  OPENCODE_DISABLE_AUTOCOMPACT: truthyWithFallback("BASEONE_DISABLE_AUTOCOMPACT", "OPENCODE_DISABLE_AUTOCOMPACT"),
  OPENCODE_DISABLE_MODELS_FETCH: truthyWithFallback("BASEONE_DISABLE_MODELS_FETCH", "OPENCODE_DISABLE_MODELS_FETCH"),
  OPENCODE_DISABLE_MOUSE: truthyWithFallback("BASEONE_DISABLE_MOUSE", "OPENCODE_DISABLE_MOUSE"),
  OPENCODE_FAKE_VCS: envWithFallback("BASEONE_FAKE_VCS", "OPENCODE_FAKE_VCS"),
  OPENCODE_SERVER_PASSWORD: envWithFallback("BASEONE_SERVER_PASSWORD", "OPENCODE_SERVER_PASSWORD"),
  OPENCODE_SERVER_USERNAME: envWithFallback("BASEONE_SERVER_USERNAME", "OPENCODE_SERVER_USERNAME"),

  // Experimental
  OPENCODE_EXPERIMENTAL: BASEONE_EXPERIMENTAL,
  OPENCODE_EXPERIMENTAL_FILEWATCHER: Config.boolean("OPENCODE_EXPERIMENTAL_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  OPENCODE_EXPERIMENTAL_DISABLE_FILEWATCHER: Config.boolean("OPENCODE_EXPERIMENTAL_DISABLE_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  OPENCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT:
    baseoneCopy === undefined ? process.platform === "win32" : truthyWithFallback("BASEONE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT", "OPENCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"),
  OPENCODE_MODELS_URL: envWithFallback("BASEONE_MODELS_URL", "OPENCODE_MODELS_URL"),
  OPENCODE_MODELS_PATH: envWithFallback("BASEONE_MODELS_PATH", "OPENCODE_MODELS_PATH"),
  OPENCODE_DB: envWithFallback("BASEONE_DB", "OPENCODE_DB"),

  OPENCODE_WORKSPACE_ID: envWithFallback("BASEONE_WORKSPACE_ID", "OPENCODE_WORKSPACE_ID"),
  OPENCODE_EXPERIMENTAL_WORKSPACES: BASEONE_EXPERIMENTAL || truthyWithFallback("BASEONE_EXPERIMENTAL_WORKSPACES", "OPENCODE_EXPERIMENTAL_WORKSPACES"),
  OPENCODE_EXPERIMENTAL_SESSION_SWITCHER: BASEONE_EXPERIMENTAL || truthyWithFallback("BASEONE_EXPERIMENTAL_SESSION_SWITCHER", "OPENCODE_EXPERIMENTAL_SESSION_SWITCHER"),

  BASEONE_EXPERIMENTAL,

  // Evaluated at access time (not module load) because tests, the CLI, and
  // external tooling set these env vars at runtime.
  get OPENCODE_DISABLE_PROJECT_CONFIG() {
    return truthyWithFallback("BASEONE_DISABLE_PROJECT_CONFIG", "OPENCODE_DISABLE_PROJECT_CONFIG")
  },
  get OPENCODE_EXPERIMENTAL_REFERENCES() {
    return enabledByExperimental("OPENCODE_EXPERIMENTAL_REFERENCES")
  },
  get OPENCODE_TUI_CONFIG() {
    return envWithFallback("BASEONE_TUI_CONFIG", "OPENCODE_TUI_CONFIG")
  },
  get OPENCODE_CONFIG_DIR() {
    return envWithFallback("BASEONE_CONFIG_DIR", "OPENCODE_CONFIG_DIR")
  },
  get OPENCODE_PURE() {
    return truthyWithFallback("BASEONE_PURE", "OPENCODE_PURE")
  },
  get OPENCODE_PLUGIN_META_FILE() {
    return envWithFallback("BASEONE_PLUGIN_META_FILE", "OPENCODE_PLUGIN_META_FILE")
  },
  get OPENCODE_CLIENT() {
    return envWithFallback("BASEONE_CLIENT", "OPENCODE_CLIENT") ?? "cli"
  },

  get BASEONE_DISABLE_PROJECT_CONFIG() {
    return truthy("BASEONE_DISABLE_PROJECT_CONFIG")
  },
  get BASEONE_TUI_CONFIG() {
    return process.env["BASEONE_TUI_CONFIG"]
  },
  get BASEONE_CONFIG_DIR() {
    return process.env["BASEONE_CONFIG_DIR"]
  },
  get BASEONE_PURE() {
    return truthy("BASEONE_PURE")
  },
  get BASEONE_PLUGIN_META_FILE() {
    return process.env["BASEONE_PLUGIN_META_FILE"]
  },
  get BASEONE_CLIENT() {
    return process.env["BASEONE_CLIENT"] ?? "cli"
  },
}
